name = "vfdashboard"
pages_build_output_dir = "./dist"
compatibility_date = "2024-11-18"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "VFDashboard"
id = "2dd5f739534b48f6b23a750e0a884a80"
